### ISSUE TITLE
Stop missing -  Neptune and Dale Mabry southbound for buses 19 and 36

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#1]
Reported on Twitter October 4, 2013 by @RichieTPA (Richard Phillips):
https://twitter.com/RichieTPA/statuses/386203170902646784

> stop missing at Neptune and Dale Mabry southbound for buses 19 and 36

**Comment by barbeau** [comment]
@haneys is going to look into this.

**Comment by haneys** [comment]
Got it!

**Comment by haneys** [comment]
Regarding #1, the stop has been modified in Trapeze which will be reflected in the GTFS data for the November 2013 markup. The new stop number id will be 1812 and the former stop id 7585 at Dale Mabry & Watrous has been made inactive.

**Comment by barbeau** [comment]
Thanks @haneys!  @wyszynskif, could you let the user who reported this on Twitter know that this issue will be resolved?  The new stop should appear in OneBusAway by Nov. 17th at the latest, which is when the current GTFS data expires.

**Comment by wyszynskif** [comment]
@barbeau I will let the customer know. Thanks @haneys!
