### ISSUE TITLE
stop_id 7434 has wrong stop name

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#10]
Current stop_name is "Fletcher @Jonh Knott Vill".

It should be "Fletcher @ John Knox Vill".

**Comment by barbeau** [comment]
cc @haneys.

**Comment by StPierreP** [comment]
corrected and will go live with the November 2015 schedule change

**Comment by barbeau** [comment]
Thanks @StPierreP!  Now that this is fixed you can close it by clicking on the "Close and comment" button at the bottom of this list.

**Comment by barbeau** [comment]
or just "Close" button, if that's what you see.
