### ISSUE TITLE
Data issue with Route 18 bus stops - stop code 4569 and stop code 2417

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#14]
@haneys and @StPierreP 

I’m seeing two stops on Route 18 that don’t show any service – stop code 4569, and stop code 2417.  They show up when you display Route 18, but don’t show any arrivals, even when the Route 18 bus is passing them.  See the screenshots below.  The bus stops for 18 North on either side of them show arrivals.

From http://tampa.onebusaway.org/enterprise/#18:

![image](https://cloud.githubusercontent.com/assets/928045/10618992/32ea2b72-7741-11e5-9d9f-b87df3a8047c.png)

![image](https://cloud.githubusercontent.com/assets/928045/10618994/358ddbe4-7741-11e5-9925-cbd834fb703e.png)

**Comment by StPierreP** [comment]
@haneys and @barbeau I am unsure why sstops are showing in OBA. I just checked the bus stops and stop trip data and those stops have removed and not assigned to the route 18. Stop 2417 details show it was later replaced by stop ID 7774. That is what I show in my stop trip data. The details for 4569 show the it was removed.

**Comment by barbeau** [comment]
@StPierreP Looks like those stops are still in the GTFS data.  From stops.txt in:
http://www.gohart.org/google/google_transit.zip

![image](https://cloud.githubusercontent.com/assets/928045/10643879/44eb8f48-77f3-11e5-941b-1d5c842b415b.png)

![image](https://cloud.githubusercontent.com/assets/928045/10643886/52c45b04-77f3-11e5-8305-8f81e5fac6a9.png)

**Comment by StPierreP** [comment]
@barbeau @haneys These stops appear to have been removed from the GTFS as I can not find them on the OBA Enterprise.
