### ISSUE TITLE
Wrong stop_code at Fletcher @ Palm Mr N-S Sta 44

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#15]
@StPierreP I think there may be a wrong stop_code in HART's GTFS data.

The stop at Fletcher @ Palm Mr N-S Sta 44 has the stop_code of 7800:
https://www.google.com/maps/place/Fletcher+@+Palm+Mr+N-S+Sta+44/@28.0691293,-82.4130058,18z/data=!4m2!3m1!1s0x88c2c795038db12f:0x29f4aac46fa6239f

...but the number 8842 is on the shelter:

![20160405_091717](https://cloud.githubusercontent.com/assets/928045/14333516/16995568-fc1d-11e5-804c-2bed4b7315ed.jpg)

Unless 8842 refers to something else?

**Comment by StPierreP** [comment]
@barbeau we have some shelters that have an ID on them such as these to identify the specific shelter. The patron should use the little ID tag. I will recommend to our bus stop folks to possibly put this ID in the rear of shelter or somewhere less noticeable to the patron. The stop should for OBA should be correct. Thank you.

**Comment by barbeau** [comment]
@StPierreP Ok, thanks!
