### ISSUE TITLE
61LX bus is not listed in app

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#3]
From user:

> The 61LX bus in Tampa Florida is not listed on your app. It runs only in the morning and afternoon.

I've confirmed that only the `61` is listed in the GTFS routes.txt, not 61LX.  If the 61LX is listed as its own route in the GTFS data, then OneBusAway should pick it up in the next GTFS update.

**Comment by barbeau** [comment]
Steve Feigenbaum's reply to user for a work-around:

> You should ask for the 61 or any of the express/limited express routes by leaving off the X or LX.  For 61LX just enter 61 and you should be OK.  Also, if you are at a 61LX stop, as an alternate,  you may enter the stop ID # instead.  The stop ID # is posted on the small white tag attached or near the bus stop sign and will have a 4 digit # on it.

@haneys Is there any reason why the 61X and LX aren't listed as separate routes in the GTFS data?  Per the GTFS spec, these really should be separate if they are presented as separate routes to the user.

**Comment by haneys** [comment]
HART routes in the scheduling software and CAD/AVL are referred to only by  their numeric route number.

**Comment by barbeau** [comment]
Thanks @haneys, I'm closing this as "won't fix" then, since we can't fix it given the constraints of the current scheduling software, which exports the GTFS data.
