### ISSUE TITLE
Real-time information missing for stop #2119

### ISSUE THREAD

**Issue by wyszynskif** [Hillsborough-Transit-Authority/hart-data#5]
Comments from @RichieTPA. Info missing from other stops on street as well.

https://twitter.com/RichieTPA/status/408623922792648704/photo/1

**Comment by barbeau** [comment]
Thanks @wyszynskif!

**Comment by barbeau** [comment]
@haneys @StPierreP Looks like this is still an issue, assuming there should be some service at the stop now:
http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_2119

**Comment by StPierreP** [comment]
@barbeau That is an hourly stop. Scheduled to arrive at 35 after the hour. I will keep an eye on it at 4:05pm and see if something populates.

**Comment by StPierreP** [comment]
@barbeau The website just updated and it shows an arrival in ~30 minutes. The issues looks to have been corrected.

**Comment by barbeau** [comment]
Ok, great, thanks @StPierreP!
