### ISSUE TITLE
Missing stop at Swann and Henderson?

### ISSUE THREAD

**Issue by wyszynskif** [Hillsborough-Transit-Authority/hart-data#8]
From Twitter:

@RichieTPA - @OBA_Tampa the stop at henderson and swann going south is still missing the stop is in front of walgreens it is for route 19. 

Might be a GFTS data issue, because the closest stop I see in that area on Route 19 heading south is Henderson and Sterling.

**Comment by barbeau** [comment]
@StPierreP I believe this is still an issue as well.  Here's the area in OBA:
http://tampa.onebusaway.org/where/standard/#m(query)q(henderson%20and%20swann)qll(28.0581,-82.4167)_(0)

**Comment by StPierreP** [comment]
@barbeau http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough Area Regional Transit_1915

Stop 1915 is the SB stop on the 19 at Swann and Henderson in front of Walgreens. Appears there are no issues currently.

**Comment by barbeau** [comment]
@StPierreP Ah, sorry - I was looking for a stop on Henderson in front of Walgreens, not on Swann in front of Walgreens.  So you're right, looks like this was fixed.
