### ISSUE TITLE
Stop #3105 "Alumni Dr @ Laurel Dr" has incorrect location

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#9]
This stop was moved a while back for construction. HART still has the temporary construction location of the stop in its GTFS data - i.e., the data was never updated when the stop returned to its old position post-construction.

The correct permanent location is:
`28.0581441,-82.4161803`

**Comment by StPierreP** [comment]
@barbeau The stop has been re-geocoded in Trapeze. Will go live with the November 2015 schedule change

**Comment by barbeau** [comment]
Thanks @StPierreP!
